---
platform: linux

image_resource:
  type: docker-image
  source: {repository: teliaoss/concourse-awscli }

inputs:
  - name: styleguide

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME:

run:
  path: sh
  args:
  - styleguide/ci/tasks/aws-s3-upload/task.sh