---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "8-alpine" }

inputs:
  - name: styleguide

params:
  update_type:
  npm_token:

outputs:
  - name: styleguide

run:
  path: sh
  args:
  - styleguide/ci/tasks/update-publish-version/task.sh
